# src/postmortem_dbt/dbt/writer.py
import re
from pathlib import Path
from rich.console import Console
from ruamel.yaml import YAML
from ..core.models import DbtTestProposal
from .manifest import DbtManifest

console = Console()
yaml = YAML()
yaml.preserve_quotes = True
yaml.width = 4096 # Prevent aggressive line wrapping

def _sanitize_filename(name: str) -> str:
    """Slugify to prevent path traversal and invalid chars."""
    sanitized = re.sub(r'[^a-z0-9_]', '_', name.lower().strip())
    if ".." in sanitized or sanitized.startswith('/') or sanitized.startswith('\\'):
        raise ValueError(f"Invalid test name (potential path traversal): {name}")
    return sanitized or "unnamed_test"

def write_test(proposal: DbtTestProposal, project_path: Path, manifest: DbtManifest, dry_run: bool = False) -> None:
    # 1. Validate target_table against manifest
    if proposal.target_table not in manifest.models_by_name:
        raise ValueError(f"Target table '{proposal.target_table}' not found in dbt manifest. Available models: {list(manifest.models_by_name.keys())[:5]}...")

    if proposal.test_type == "singular":
        _write_singular_test(proposal, project_path, dry_run)
    else:
        _write_generic_test(proposal, project_path, manifest, dry_run)

def _write_singular_test(proposal: DbtTestProposal, project_path: Path, dry_run: bool) -> None:
    tests_dir = project_path / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)
    
    safe_name = _sanitize_filename(proposal.test_name)
    file_path = tests_dir / f"{safe_name}.sql"
    
    if file_path.exists():
        raise FileExistsError(f"Test file already exists: {file_path}. Refusing to overwrite.")
    
    # Collapse multi-line summary to prevent SQL comment breakout
    safe_summary = proposal.incident_summary.replace('\n', ' ').replace('\r', '').strip()
    
    content = f"""-- Generated by postmortem-to-dbt
-- Incident: {safe_summary}
-- Rationale: {proposal.rationale}

{proposal.test_code.strip()}
"""
    if dry_run:
        console.print(f"[yellow]📝 [DRY RUN] Would create file:[/yellow] {file_path}")
        console.print(f"[dim]{content}[/dim]")
    else:
        file_path.write_text(content, encoding="utf-8")
        console.print(f"[green]✅ Created singular test:[/green] {file_path}")

def _write_generic_test(proposal: DbtTestProposal, project_path: Path, manifest: DbtManifest, dry_run: bool) -> None:
    node = manifest.get_model_node(proposal.target_table)
    
    # 1. Robustly parse patch_path: format is "project_name://relative/path/to/file.yml"
    raw_patch_path = node.get('patch_path', '') if node else ''
    if raw_patch_path and '://' in raw_patch_path:
        relative_path = raw_patch_path.split('://', 1)[1]
        file_path = project_path / relative_path
    else:
        # 2. Fallback if the model has no YAML file yet (unpatched model)
        file_path = project_path / "models" / "schema.yml"
        console.print(f"[yellow]⚠️ No valid patch_path found for '{proposal.target_table}'. Defaulting to {file_path}[/yellow]")

    # Ensure the directory exists (handles cases where the YAML is in a subfolder like models/marts/)
    file_path.parent.mkdir(parents=True, exist_ok=True)

    if file_path.exists():
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                schema_data = yaml.load(f) or {"version": 2, "models": []}
        except Exception as e:
            raise ValueError(f"Failed to parse existing YAML at {file_path}: {e}. Fix the YAML manually before running.")
    else:
        schema_data = {"version": 2, "models": []}

    if "models" not in schema_data:
        schema_data["models"] = []

    model_entry = next((m for m in schema_data["models"] if m.get("name") == proposal.target_table), None)
    if not model_entry:
        model_entry = {"name": proposal.target_table}
        schema_data["models"].append(model_entry)

    if proposal.target_column:
        if "columns" not in model_entry:
            model_entry["columns"] = []
        col_entry = next((c for c in model_entry["columns"] if c.get("name") == proposal.target_column), None)
        if not col_entry:
            col_entry = {"name": proposal.target_column}
            model_entry["columns"].append(col_entry)
        
        # Support dbt 1.8+ data_tests, fallback to tests
        test_key = "data_tests" if "data_tests" in col_entry else "tests"
        if test_key not in col_entry:
            col_entry[test_key] = []
        target_tests = col_entry[test_key]
    else:
        test_key = "data_tests" if "data_tests" in model_entry else "tests"
        if test_key not in model_entry:
            model_entry[test_key] = []
        target_tests = model_entry[test_key]

    try:
        new_test = yaml.load(proposal.test_code)
        if isinstance(new_test, list):
            target_tests.extend(new_test)
        else:
            target_tests.append(new_test)
    except Exception as e:
        raise ValueError(f"LLM generated invalid YAML for test code: {proposal.test_code}. Error: {e}")

    if dry_run:
        console.print(f"[yellow]📝 [DRY RUN] Would update file:[/yellow] {file_path}")
        console.print(f"[dim]...adding test to {proposal.target_table}[/dim]")
    else:
        with open(file_path, 'w', encoding='utf-8') as f:
            yaml.dump(schema_data, f)
        console.print(f"[green]✅ Updated generic test in:[/green] {file_path}")