# src/postmortem_dbt/dbt/writer.py

import yaml
from pathlib import Path
from rich.console import Console
from ..core.models import DbtTestProposal

console = Console()

def write_test(proposal: DbtTestProposal, project_path: Path, dry_run: bool = False) -> None:
    if not project_path.exists():
        console.print(f"[red]Error:[/red] Project path does not exist: {project_path}")
        return

    if proposal.test_type == "singular":
        _write_singular_test(proposal, project_path, dry_run)
    else:
        _write_generic_test(proposal, project_path, dry_run)


def _write_singular_test(proposal: DbtTestProposal, project_path: Path, dry_run: bool) -> None:
    tests_dir = project_path / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)
    file_path = tests_dir / f"{proposal.test_name}.sql"
    
    content = f"""-- Generated by postmortem-to-dbt
-- Incident: {proposal.incident_summary}
-- Rationale: {proposal.rationale}

{proposal.test_code}
"""
    if dry_run:
        console.print(f"[yellow]📝 [DRY RUN] Would create file:[/yellow] {file_path}")
        console.print(f"[dim]{content}[/dim]")
    else:
        file_path.write_text(content, encoding="utf-8")
        console.print(f"[green]✅ Created singular test:[/green] {file_path}")


def _write_generic_test(proposal: DbtTestProposal, project_path: Path, dry_run: bool) -> None:
    models_dir = project_path / "models"
    models_dir.mkdir(parents=True, exist_ok=True)
    file_path = models_dir / "schema.yml"
    
    if file_path.exists():
        with open(file_path, 'r', encoding='utf-8') as f:
            try:
                schema_data = yaml.safe_load(f)
                if not isinstance(schema_data, dict):
                    schema_data = {"version": 2, "models": []}
            except yaml.YAMLError:
                schema_data = {"version": 2, "models": []}
    else:
        schema_data = {"version": 2, "models": []}

    if "models" not in schema_data:
        schema_data["models"] = []

    model_entry = next((m for m in schema_data["models"] if m.get("name") == proposal.target_table), None)
    if not model_entry:
        model_entry = {"name": proposal.target_table}
        schema_data["models"].append(model_entry)

    if proposal.target_column:
        if "columns" not in model_entry:
            model_entry["columns"] = []
        
        col_entry = next((c for c in model_entry["columns"] if c.get("name") == proposal.target_column), None)
        if not col_entry:
            col_entry = {"name": proposal.target_column}
            model_entry["columns"].append(col_entry)
        
        # SAFE ACCESS: Ensure 'tests' key exists before appending
        if "tests" not in col_entry:
            col_entry["tests"] = []
        target_tests = col_entry["tests"]
    else:
        # Table-level test
        if "tests" not in model_entry:
            model_entry["tests"] = []
        target_tests = model_entry["tests"]

    # Parse the new test and append it safely
    try:
        new_test = yaml.safe_load(proposal.test_code)
        if isinstance(new_test, list):
            target_tests.extend(new_test)
        else:
            target_tests.append(new_test)
    except yaml.YAMLError:
        # Fallback: append as raw string if parsing fails
        target_tests.append(proposal.test_code)

    if dry_run:
        console.print(f"[yellow]📝 [DRY RUN] Would update file:[/yellow] {file_path}")
        console.print(f"[dim]{yaml.dump(schema_data, sort_keys=False)}[/dim]")
    else:
        with open(file_path, 'w', encoding='utf-8') as f:
            yaml.dump(schema_data, f, sort_keys=False, allow_unicode=True)
        console.print(f"[green]✅ Updated generic test in:[/green] {file_path}")